#!/usr/bin/env bash

# Makes global Git configuration file with my settings and prints the current
# global git config. Existing file is overwritten without warning or backup!
#
# Latest revision: 2025-02-04
#
# Created and unlicensed by Mikołaj Bartnicki <mikolaj@bartnicki.org>;
# please read UNLICENSE file for details.

# Stop and exit on first error.
set -e

code_excludes_file="~/.gitignore"
commit_gpgsign="true"
core_autocrlf="true" # Set "false" for Linux, TODO: detect OS to autoset this.
core_editor="vim"
gpg_format="ssh"
pull_rebase="false"
push_auto_setup_remote="true"
user_email="mikolaj@bartnicki.org"
user_name="Mikołaj Bartnicki"
user_signingkey="~/.ssh/id_ed25519.pub"

write_log() {
    echo "::::$0::${FUNCNAME[1]}()"
}

main() {
    write_log

    git config --global commit.gpgsign "$commit_gpgsign"
    git config --global core.autocrlf "$core_autocrlf"
    git config --global core.editor "$core_editor"
    git config --global core.excludesFile "$code_excludes_file"
    git config --global gpg.format "$gpg_format"
    git config --global pull.rebase "$pull_rebase"
    git config --global push.autoSetupRemote "$push_auto_setup_remote"
    git config --global user.email "$user_email"
    git config --global user.name "$user_name"
    git config --global user.signingkey "$user_signingkey"

    git config --global --list
}

main
